Criado tela para visualizar curtidas
Materdei-Sistemas/instavue pull request #20
Opened 2020-08-27 00:22 UTC by guilhermeemanuelpires

2020-08-27 00:29 UTC, FelipeHannemann7 commented on client/src/App.vue
> +      <router-link to="/Curtidas">Curtidas</router-link>
@guilhermeemanuelpires  dou como sugestão deixar com letras minusculas as rotas substituindo o /Curtidas por /curtidas

2020-08-27 00:31 UTC, FelipeHannemann7 commented on client/src/router/index.js
> +  },{
@guilhermeemanuelpires manter padrão de identação dos blocos acima, quebrando a linha após a virgula

2020-08-27 00:32 UTC, FelipeHannemann7 requested changes
@guilhermeemanuelpires Visualizar e ajustar os pontos necessários

2020-08-27 12:24 UTC, luizcarraro commented on client/src/App.vue
> +      <router-link to="/Curtidas">Curtidas</router-link>
Perfeito! O ideal é manter em minúsculo. Favor Corrigir

2020-08-27 12:26 UTC, luizcarraro requested changes
Realizar alterações sugeridas pelo Felipe

2020-09-02 22:44 UTC, luizcarraro commented on client/src/App.vue
> +      <router-link to="/Curtidas">Curtidas</router-link>
```suggestion
      <router-link to="/curtidas">Curtidas</router-link>
```

2020-09-02 22:45 UTC, luizcarraro approved these changes

2020-09-02 22:46 UTC, merged